### ISSUE TITLE
Oil Rig

### ISSUE THREAD

**Issue by jbarros35** [IceReaper/KKnD#37] opened 2019-08-04 11:45 UTC
Hi guys, in game, how can I use and capture those oil rigs neutral?
Sorry bother you here but I could not find any information about it.

**Comment by Dzierzan** [comment] 2019-08-09 20:36
Use saboteurs. They can capture buildings or reinforce your own buildings.

**Comment by IceReaper** [comment] 2020-05-26 21:31
Not a bug, closing

**Closed by IceReaper** 2020-05-26 21:31 UTC
